name: Node.js CI

on: [push]

jobs:
  run:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - name: github.ref
      run: echo ${{github.ref}}

    - name: matrix.node-version
      run: echo ${{matrix.node-version}}

    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Installing dependencies
      run: make install
      
    - name: Passing tests
      run: make test
      env:
        NYC_REPORTERS: "--reporter=text --reporter=lcov"

    - if: github.ref == 'refs/heads/master' && matrix.node-version == '12.x'
      name: Build docs
      run: make docs

    - if: github.ref == 'refs/heads/master' && matrix.node-version == '12.x'
      name: Deploy docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./docs

    - if: github.ref == 'refs/heads/master' && matrix.node-version == '12.x'
      name: Publishing to codecov
      run: make codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - if: github.ref == 'refs/heads/master' && matrix.node-version == '12.x'
      name: Publishing to coveralls
      run: make coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

    - if: github.ref == 'refs/heads/master' && matrix.node-version == '12.x'
      name: Publishing to codeclimate
      run: make codeclimate
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
