name: Node.js CI

on: [push]

jobs:
  run:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - name: github.ref
      run: echo ${{github.ref}}

    - name: matrix.node
      run: echo ${{matrix.node}}

    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Installing dependencies
      run: make install
      
    - name: Passing tests
      run: make test

    - name: Publishing to codecov
      run: make codecov
      if: github.ref == 'refs/heads/master' && matrix.node-version == '12.x'
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  # coverage:

  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [12.x]
    
  #   steps:
  #   - name: Publishing to coveralls
  #     run: make coveralls
  #     # if: github.ref == 'master'
  #     env:
  #       COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      
  #   - name: Publishing to codecov
  #     run: make codecov
  #     if: github.ref == 'master'
  #     env:
  #       CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
